
- name:
  delegate_to: 127.0.0.1
  command: |
    perl -e 'print " " x (24 - length( '{{ element_subdomain }}' ))';
  register: dns_spaces

- debug:
    msg: 
    - "You're server has been created! You now need to configure your DNS to have the following records:"
    - "Type    Host                    Priority  Weight  Port   Target
    - "A       matrix                  -         -       -      {{ server_ipv4 }}
    - "A       matrix                  -         -       -      {{ server_ipv6 }}
    - "CNAME   {{ element_subdomain }}{{ dns_spaces.stdout }}-         -       -      matrix.{{ matrix_domain }}
    - "CNAME   jitsi                   -         -       -      matrix.{{ matrix_domain }}
    - "SRV     _matrix-identity._tcp   10        0       443    matrix.{{ matrix_domain }}
    - "-"
    - Setting the IPv6 record is optional. If you need help doing this please contact us.
    - "-"
    - You also decided that your base domain was already in use, you'll need to configure
    - "a .well-known entry for your existing web service before you proceed:" 
    - https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/configuring-well-known.md
  when: base_domain_used == 'true'

- debug:
    msg: 
    - You're server has been created! You now need to configure your DNS to have the following records:
    - 
    - Type    Host                    Priority  Weight  Port   Target
    - A       matrix                  -         -       -      {{ server_ipv4 }}
    - A       matrix                  -         -       -      {{ server_ipv6 }}
    - CNAME   {{ element_subdomain }}{{ dns_spaces.stdout }}-         -       -      matrix.{{ matrix_domain }}
    - CNAME   jitsi                   -         -       -      matrix.{{ matrix_domain }}
    - SRV     _matrix-identity._tcp   10        0       443    matrix.{{ matrix_domain }}
    - 
    - Setting the IPv6 record is optional. If you need help doing this please contact us.
  when: base_domain_used == 'false'

