
- debug:
    msg: "{{ server_ipv4 }}"

- debug:
    msg: "{{ server_ipv6 }}"
  when: server_ipv6 is defined

- name: accept new ssh fingerprints (Not safe against MITM) 
  delegate_to: 127.0.0.1                                     
  command: |
    ssh-keyscan -H "{{ server_ipv4 }}" >> ~/.ssh/known_hosts    

- name: Test if SSH is possible with ipv4
  delegate_to: "{{ server_ipv4 }}"
  command: echo success
  register: echo_output

- debug:
    msg: "{{ echo_output.stdout }}"

- name: Disable password authentication
  delegate_to: "{{ server_ipv4 }}"
  lineinfile:
    path: /etc/ssh/sshd_config
    line: 'PasswordAuthentication no'

- name: Restart SSH
  delegate_to: "{{ server_ipv4 }}"
  service:
    name: ssh
    state: restarted

