

# Append to server_vars.yml variable file

- name: Add slug_size line to server_vars.yml file locally on AWX
  delegate_to: 127.0.0.1
  lineinfile:
    dest: '/var/lib/awx/projects/clients/{{ member_id }}/{{ subscription_id }}/server_vars.yml'
    line: 'slug_size: {{ slug_size }}'
    mode: '0600'
    state: present
  when: subscription_type == "digitalocean"

- name: Add do_droplet_region line to server_vars.yml file locally on AWX
  delegate_to: 127.0.0.1
  lineinfile:
    dest: '/var/lib/awx/projects/clients/{{ member_id }}/{{ subscription_id }}/server_vars.yml'
    line: 'do_droplet_region: {{ do_droplet_region }}'
    mode: '0600'
    state: present
    create: yes
  when: subscription_type == "digitalocean"

- name: Add do_droplet_id line to server_vars.yml file locally on AWX
  delegate_to: 127.0.0.1
  lineinfile:
    dest: '/var/lib/awx/projects/clients/{{ member_id }}/{{ subscription_id }}/server_vars.yml'
    line: 'do_droplet_id: {{ new_server_info.data.droplet.id }}'
    mode: '0600'
    state: present
  when: subscription_type == "digitalocean"

- name: Add server_ipv4 line to server_vars.yml file locally on AWX
  delegate_to: 127.0.0.1
  lineinfile:
    dest: '/var/lib/awx/projects/clients/{{ member_id }}/{{ subscription_id }}/server_vars.yml'
    line: 'server_ipv4: {{ server_ipv4 }}'
    mode: '0600'
    state: present
  when: server_ipv4|length > 0

- name: Add server_ipv6 line to server_vars.yml file locally on AWX
  delegate_to: 127.0.0.1
  lineinfile:
    dest: '/var/lib/awx/projects/clients/{{ member_id }}/{{ subscription_id }}/server_vars.yml'
    line: 'server_ipv6: {{ server_ipv6 }}'
    mode: '0600'
    state: present
  when: server_ipv6|length > 0

- name: Add matrix_domain line to server_vars.yml file locally on AWX
  delegate_to: 127.0.0.1
  lineinfile:
    dest: '/var/lib/awx/projects/clients/{{ member_id }}/{{ subscription_id }}/server_vars.yml'
    line: 'matrix_domain: {{ matrix_domain }}'
    mode: '0600'
    state: present

- name: Add plan_title line to server_vars.yml file locally on AWX
  delegate_to: 127.0.0.1
  lineinfile:
    dest: '/var/lib/awx/projects/clients/{{ member_id }}/{{ subscription_id }}/server_vars.yml'
    line: 'plan_title: {{ plan_title }}'
    mode: '0600'
    state: present
  when: plan_title is defined

#- name: Add base_mau_limit line to server_vars.yml file locally on AWX
#  delegate_to: 127.0.0.1
#  lineinfile:
#    dest: '/var/lib/awx/projects/clients/{{ member_id }}/{{ subscription_id }}/server_vars.yml'
#    line: 'base_mau_limit: {{ base_mau_limit }}'
#    mode: '0600'
#    state: present
    
#- name: Set MAU multiplier if not defined
#  delegate_to: 127.0.0.1
#  set_fact:
#    mau_multiplier: "1"
#  when: mau_multiplier is not defined
  
#- name: Add mau_multiplier line to server_vars.yml file locally on AWX
#  delegate_to: 127.0.0.1
#  lineinfile:
#    dest: '/var/lib/awx/projects/clients/{{ member_id }}/{{ subscription_id }}/server_vars.yml'
#    line: 'mau_multiplier: {{ mau_multiplier }}'
#    mode: '0600'
#    state: present

- name: Wait for ssh connection to become available, with 5 seconds between checks
  delegate_to: "{{ server_ip_final }}"
  wait_for_connection:
    sleep: 5

- name: Create /matrix/awx config directory
  delegate_to: "{{ server_ip_final }}"
  file:
    path: /matrix/awx
    state: directory
    mode: '0700'

# Append to extra_vars.json variable file for launching deploy scripts

- name: Add target line to extra_vars.json file locally on AWX
  delegate_to: 127.0.0.1
  lineinfile:
    insertafter: '{'
    dest: '/var/lib/awx/projects/clients/{{ member_id }}/{{ subscription_id }}/extra_vars.json'
    line: '  "target": "matrix.{{ matrix_domain }}",'
    mode: '0600'
    state: present

- name: Add target line to extra_vars.json file locally on AWX
  delegate_to: 127.0.0.1
  lineinfile:
    insertafter: '{'
    dest: '/var/lib/awx/projects/clients/{{ member_id }}/{{ subscription_id }}/extra_vars.json'
    line: '  "matrix_domain": "{{ matrix_domain }}",'
    mode: '0600'
    state: present

- name: Add matrix_awx_enabled line to extra_vars.json file locally on AWX
  delegate_to: 127.0.0.1
  lineinfile:
    insertafter: '{'
    dest: '/var/lib/awx/projects/clients/{{ member_id }}/{{ subscription_id }}/extra_vars.json'
    line: '  "matrix_awx_enabled": "true",'
    mode: '0600'
    state: present

# Create matrix_vars.yml variable file

- name: Install password generation script
  delegate_to: 127.0.0.1
  copy:
    src: ./roles/spawn-server/scripts/generate-initial-passwords.sh
    dest: /var/lib/awx/projects/hosting/generate-initial-passwords.sh
    mode: '0700'

- name: Check if matrix_vars.yml file already exists on AWX
  delegate_to: 127.0.0.1
  stat: 
    path: '/var/lib/awx/projects/clients/{{ member_id }}/{{ subscription_id }}/matrix_vars.yml'
  register: varsfile

- name: Generate initial matrix_vars.yml on AWX if it does not exist
  delegate_to: 127.0.0.1
  command: /var/lib/awx/projects/hosting/generate-initial-passwords.sh "{{ matrix_domain }}" "{{ element_subdomain }}" "{{ client_email }}" "/var/lib/awx/projects/clients/{{ member_id }}/{{ subscription_id }}/matrix_vars.yml"
  when: varsfile.stat.exists == false
  
- name: Over-write Element subdomain value if changed
  delegate_to: 127.0.0.1
  lineinfile:
    dest: '/var/lib/awx/projects/clients/{{ member_id }}/{{ subscription_id }}/matrix_vars.yml'
    regexp: "^#? *{{ item.key | regex_escape() }}:"
    line: "{{ item.key }}: {{ item.value }}"
    insertafter: '# Element Settings'
    mode: '0600'
    state: present
  with_dict:
    'matrix_server_fqn_element': '{{ element_subdomain }}.{{ matrix_domain }}'
  when: varsfile.stat.exists == true

- name: Over-write client_email value if changed
  delegate_to: 127.0.0.1
  lineinfile:
    dest: '/var/lib/awx/projects/clients/{{ member_id }}/{{ subscription_id }}/matrix_vars.yml'
    regexp: "^#? *{{ item.key | regex_escape() }}:"
    line: "  {{ item.key }}: {{ item.value }}"
    insertafter: '# Synapse Extension'
    mode: '0600'
    state: present
  with_dict:
    'admin_contact': "'mailto:{{ client_email }}'"
  when: varsfile.stat.exists == true

- name: Add matrix_nginx_proxy_base_domain_serving_enabled line to matrix_vars.yml file locally on AWX
  delegate_to: 127.0.0.1
  lineinfile:
    dest: '/var/lib/awx/projects/clients/{{ member_id }}/{{ subscription_id }}/matrix_vars.yml'
    insertafter: '# Base Domain Settings'
    line: 'matrix_nginx_proxy_base_domain_serving_enabled: false'
    mode: '0600'
    state: present
  when: base_domain_used|bool == true

- name: Add matrix_nginx_proxy_base_domain_serving_enabled line to matrix_vars.yml file locally on AWX
  delegate_to: 127.0.0.1
  lineinfile:
    dest: '/var/lib/awx/projects/clients/{{ member_id }}/{{ subscription_id }}/matrix_vars.yml'
    insertafter: '# Base Domain Settings'
    line: 'matrix_nginx_proxy_base_domain_serving_enabled: true'
    mode: '0600'
    state: present
  when: base_domain_used|bool == false

- name: Add matrix_nginx_proxy_base_domain_serving_enabled line to matrix_vars.yml file locally on AWX
  delegate_to: 127.0.0.1
  lineinfile:
    dest: '/var/lib/awx/projects/clients/{{ member_id }}/{{ subscription_id }}/matrix_vars.yml'
    insertafter: '# Base Domain Settings'
    line: 'matrix_nginx_proxy_base_domain_homepage_enabled: true'
    mode: '0600'
    state: present
  when: base_domain_used|bool == false

- name: Add matrix_jitsi_timezone line to matrix_vars.yml file locally on AWX
  delegate_to: 127.0.0.1
  lineinfile:
    dest: '/var/lib/awx/projects/clients/{{ member_id }}/{{ subscription_id }}/matrix_vars.yml'
    insertafter: '# Jitsi Settings'
    line: 'matrix_jitsi_timezone: "{{ matrix_jitsi_timezone }}"'
    mode: '0600'
    state: present
  when: matrix_jitsi_timezone is defined

- name: Disable limit_usage_by_mau line to matrix_vars.yml file
  delegate_to: 127.0.0.1
  lineinfile:
    dest: '/var/lib/awx/projects/clients/{{ member_id }}/{{ subscription_id }}/matrix_vars.yml'
    insertbefore: '# End Synapse Extension'
    line: '  limit_usage_by_mau: False'
    mode: '0600'
    state: present

#- name: Add mau_max_value line to matrix_vars.yml file if mau_limit is defined
#  delegate_to: 127.0.0.1
#  lineinfile:
#    dest: '/var/lib/awx/projects/clients/{{ member_id }}/{{ subscription_id }}/matrix_vars.yml'
#    insertbefore: '# End Synapse Extension'
#    line: '  max_mau_value: {{ base_mau_limit * mau_multiplier + 1 }}'
#    mode: '0600'
#    state: present

# Copy organisation.yml, server_vars.yml, extra_vars.yml, matrix_vars.yml

- name: Copy organisation.yml variables file to target
  delegate_to: "{{ server_ip_final }}"
  copy:
    src: '/var/lib/awx/projects/clients/{{ member_id }}/organisation.yml'
    dest: /matrix/awx/organisation.yml
    mode: '0660'

- name: Copy server_vars.yml variables file to target
  delegate_to: "{{ server_ip_final }}"
  copy:
    src: '/var/lib/awx/projects/clients/{{ member_id }}/{{ subscription_id }}/server_vars.yml'
    dest: /matrix/awx/server_vars.yml
    mode: '0660'

- name: Copy extra_vars.json variables file to target
  delegate_to: "{{ server_ip_final }}"
  copy:
    src: '/var/lib/awx/projects/clients/{{ member_id }}/{{ subscription_id }}/extra_vars.json'
    dest: /matrix/awx/extra_vars.json
    mode: '0660'

- name: Copy matrix_vars.yml variables file to target
  delegate_to: "{{ server_ip_final }}"
  copy:
    src: '/var/lib/awx/projects/clients/{{ member_id }}/{{ subscription_id }}/matrix_vars.yml'
    dest: /matrix/awx/matrix_vars.yml
    mode: '0660'


