

# Append to server_vars.yml variable file

- name: Add slug_size line to server_vars.yml file locally on AWX
  delegate_to: 127.0.0.1
  lineinfile:
    dest: '/var/lib/awx/projects/clients/{{ member_id }}/{{ subscription_id }}/server_vars.yml'
    line: 'slug_size: {{ slug_size }}'
    mode: '0600'
    state: present
  when: slug_size is defined

- name: Add swap_size line to server_vars.yml file locally on AWX
  delegate_to: 127.0.0.1
  lineinfile:
    dest: '/var/lib/awx/projects/clients/{{ member_id }}/{{ subscription_id }}/server_vars.yml'
    line: 'swap_size: {{ swap_size }}'
    mode: '0600'
    state: present

- name: Add do_droplet_region line to server_vars.yml file locally on AWX
  delegate_to: 127.0.0.1
  lineinfile:
    dest: '/var/lib/awx/projects/clients/{{ member_id }}/{{ subscription_id }}/server_vars.yml'
    line: 'do_droplet_region: {{ do_droplet_region }}'
    mode: '0600'
    state: present
    create: yes
  when: do_droplet_region is defined

- name: Add do_droplet_id line to server_vars.yml file locally on AWX
  delegate_to: 127.0.0.1
  lineinfile:
    dest: '/var/lib/awx/projects/clients/{{ member_id }}/{{ subscription_id }}/server_vars.yml'
    line: 'do_droplet_id: {{ new_server_info.data.droplet.id }}'
    mode: '0600'
    state: present
  when: new_server_info is defined

- name: Add server_ipv4 line to server_vars.yml file locally on AWX
  delegate_to: 127.0.0.1
  lineinfile:
    dest: '/var/lib/awx/projects/clients/{{ member_id }}/{{ subscription_id }}/server_vars.yml'
    line: 'server_ipv4: {{ server_ipv4 }}'
    mode: '0600'
    state: present

- name: Add server_ipv6 line to server_vars.yml file locally on AWX
  delegate_to: 127.0.0.1
  lineinfile:
    dest: '/var/lib/awx/projects/clients/{{ member_id }}/{{ subscription_id }}/server_vars.yml'
    line: 'server_ipv6: {{ server_ipv6 }}'
    mode: '0600'
    state: present
  when: server_ipv6 is defined

- name: Add matrix_domain line to server_vars.yml file locally on AWX
  delegate_to: 127.0.0.1
  lineinfile:
    dest: '/var/lib/awx/projects/clients/{{ member_id }}/{{ subscription_id }}/server_vars.yml'
    line: 'matrix_domain: {{ matrix_domain }}'
    mode: '0600'
    state: present

- name: Add plan_title line to server_vars.yml file locally on AWX
  delegate_to: 127.0.0.1
  lineinfile:
    dest: '/var/lib/awx/projects/clients/{{ member_id }}/{{ subscription_id }}/server_vars.yml'
    line: 'plan_title: {{ plan_title }}'
    mode: '0600'
    state: present
  when: plan_title is defined

- name: Wait for ssh connection to become available, with 5 seconds between checks
  delegate_to: "{{ server_ipv4 }}"
  wait_for_connection:
    sleep: 5

- name: create /matrix/awx config directory
  delegate_to: "{{ server_ipv4 }}"
  file:
    path: /matrix/awx
    state: directory
    mode: '0700'

# Create target.yml variable file for launching deploy scripts

- name: Add target line to extra_vars.yml file locally on AWX
  delegate_to: 127.0.0.1
  lineinfile:
    dest: '/var/lib/awx/projects/clients/{{ member_id }}/{{ subscription_id }}/extra_vars.yml'
    line: 'target: "matrix.{{ matrix_domain }}"'
    mode: '0600'
    state: present

- name: Add target line to extra_vars.yml file locally on AWX
  delegate_to: 127.0.0.1
  lineinfile:
    dest: '/var/lib/awx/projects/clients/{{ member_id }}/{{ subscription_id }}/extra_vars.yml'
    line: 'matrix_domain: "{{ matrix_domain }}"'
    mode: '0600'
    state: present

- name: Add matrix_awx_enabled line to extra_vars.yml file locally on AWX
  delegate_to: 127.0.0.1
  lineinfile:
    dest: '/var/lib/awx/projects/clients/{{ member_id }}/{{ subscription_id }}/extra_vars.yml'
    line: 'matrix_awx_enabled: true'
    mode: '0600'
    state: present

# Create matrix_vars.yml variable file

- name: Install password generation script
  delegate_to: 127.0.0.1
  copy:
    src: ./inventory/scripts/generate-initial-passwords.sh
    dest: /var/lib/awx/projects/hosting/generate-initial-passwords.sh
    mode: '0700'

- name: Check if matrix_vars.yml file already exists on AWX
  delegate_to: 127.0.0.1
  stat: 
    path: '/var/lib/awx/projects/clients/{{ member_id }}/{{ subscription_id }}/matrix_vars.yml'
  register: varsfile

- name: Generate initial matrix_vars.yml on AWX if it does not exist
  delegate_to: 127.0.0.1
  command: /var/lib/awx/projects/hosting/generate-initial-passwords.sh "{{ matrix_domain }}" "{{ element_subdomain }}" "{{ client_email }}" "/var/lib/awx/projects/clients/{{ member_id }}/{{ subscription_id }}/matrix_vars.yml"
  when: varsfile.stat.exists == false

- name: Add matrix_nginx_proxy_base_domain_serving_enabled line to matrix_vars.yml file locally on AWX
  delegate_to: 127.0.0.1
  lineinfile:
    dest: '/var/lib/awx/projects/clients/{{ member_id }}/{{ subscription_id }}/matrix_vars.yml'
    insertafter: '# Base Domain Settings'
    line: 'matrix_nginx_proxy_base_domain_serving_enabled: false'
    mode: '0600'
    state: present
  when: base_domain_used|bool == true

- name: Add matrix_nginx_proxy_base_domain_serving_enabled line to matrix_vars.yml file locally on AWX
  delegate_to: 127.0.0.1
  lineinfile:
    dest: '/var/lib/awx/projects/clients/{{ member_id }}/{{ subscription_id }}/matrix_vars.yml'
    insertafter: '# Base Domain Settings'
    line: 'matrix_nginx_proxy_base_domain_serving_enabled: true'
    mode: '0600'
    state: present
  when: base_domain_used|bool == false

- name: Add matrix_nginx_proxy_base_domain_serving_enabled line to matrix_vars.yml file locally on AWX
  delegate_to: 127.0.0.1
  lineinfile:
    dest: '/var/lib/awx/projects/clients/{{ member_id }}/{{ subscription_id }}/matrix_vars.yml'
    insertafter: '# Base Domain Settings'
    line: 'matrix_nginx_proxy_base_domain_homepage_enabled: true'
    mode: '0600'
    state: present
  when: base_domain_used|bool == false

- name: Add matrix_jitsi_timezone line to matrix_vars.yml file locally on AWX
  delegate_to: 127.0.0.1
  lineinfile:
    dest: '/var/lib/awx/projects/clients/{{ member_id }}/{{ subscription_id }}/matrix_vars.yml'
    insertafter: '# Jitsi Settings'
    line: 'matrix_jitsi_timezone: "{{ matrix_jitsi_timezone }}"'
    mode: '0600'
    state: present
  when: matrix_jitsi_timezone is defined

- name: Add limit_usage_by_mau line to matrix_vars.yml file if mau_limit is defined
  delegate_to: 127.0.0.1
  lineinfile:
    dest: '/var/lib/awx/projects/clients/{{ member_id }}/{{ subscription_id }}/matrix_vars.yml'
    insertbefore: '# End Synapse Extension'
    line: '  limit_usage_by_mau: True'
    mode: '0600'
    state: present
  when: mau_limit is defined

- name: Add mau_max_value line to matrix_vars.yml file if mau_limit is defined
  delegate_to: 127.0.0.1
  lineinfile:
    dest: '/var/lib/awx/projects/clients/{{ member_id }}/{{ subscription_id }}/matrix_vars.yml'
    insertbefore: '# End Synapse Extension'
    line: '  max_mau_value: "{{ mau_limit }}"'
    mode: '0600'
    state: present
  when: mau_limit is defined


