
# Append to server_vars.yml variable file

- name: Add slug_size line to server_vars.yml file locally on AWX
  delegate_to: 127.0.0.1
  lineinfile:
    dest: '/var/lib/awx/projects/clients/{{ member_id }}/{{ subscription_id }}/server_vars.yml'
    line: 'slug_size: {{ slug_size }}'
    mode: '0600'
    state: present
  when: subscription_type == "digitalocean"

- name: Add do_droplet_region line to server_vars.yml file locally on AWX
  delegate_to: 127.0.0.1
  lineinfile:
    dest: '/var/lib/awx/projects/clients/{{ member_id }}/{{ subscription_id }}/server_vars.yml'
    line: 'do_droplet_region: {{ do_droplet_region }}'
    mode: '0600'
    state: present
    create: yes
  when: subscription_type == "digitalocean"

- name: Add do_droplet_id line to server_vars.yml file locally on AWX
  delegate_to: 127.0.0.1
  lineinfile:
    dest: '/var/lib/awx/projects/clients/{{ member_id }}/{{ subscription_id }}/server_vars.yml'
    line: 'do_droplet_id: {{ new_server_info.data.droplet.id }}'
    mode: '0600'
    state: present
  when: subscription_type == "digitalocean"

- name: Add server_ipv4 line to server_vars.yml file locally on AWX
  delegate_to: 127.0.0.1
  lineinfile:
    dest: '/var/lib/awx/projects/clients/{{ member_id }}/{{ subscription_id }}/server_vars.yml'
    line: 'server_ipv4: {{ server_ipv4 }}'
    mode: '0600'
    state: present
  when: server_ipv4|length > 0

- name: Add server_ipv6 line to server_vars.yml file locally on AWX
  delegate_to: 127.0.0.1
  lineinfile:
    dest: '/var/lib/awx/projects/clients/{{ member_id }}/{{ subscription_id }}/server_vars.yml'
    line: 'server_ipv6: {{ server_ipv6 }}'
    mode: '0600'
    state: present
  when: server_ipv6|length > 0

- name: Add matrix_domain line to server_vars.yml file locally on AWX
  delegate_to: 127.0.0.1
  lineinfile:
    dest: '/var/lib/awx/projects/clients/{{ member_id }}/{{ subscription_id }}/server_vars.yml'
    line: 'matrix_domain: {{ matrix_domain }}'
    mode: '0600'
    state: present

- name: Add plan_title line to server_vars.yml file locally on AWX
  delegate_to: 127.0.0.1
  lineinfile:
    dest: '/var/lib/awx/projects/clients/{{ member_id }}/{{ subscription_id }}/server_vars.yml'
    line: 'plan_title: {{ plan_title }}'
    mode: '0600'
    state: present
  when: plan_title is defined

- name: Wait for ssh connection to become available, with 5 seconds between checks
  delegate_to: "{{ server_ip_final }}"
  wait_for_connection:
    sleep: 5

- name: Create /matrix/awx config directory
  delegate_to: "{{ server_ip_final }}"
  file:
    path: /matrix/awx
    state: directory
    mode: '0700'

# Append to extra_vars.json variable file for launching deploy scripts

- name: Add target line to extra_vars.json file locally on AWX
  delegate_to: 127.0.0.1
  lineinfile:
    insertafter: '{'
    dest: '/var/lib/awx/projects/clients/{{ member_id }}/{{ subscription_id }}/extra_vars.json'
    line: '  "target": "matrix.{{ matrix_domain }}",'
    mode: '0600'
    state: present

- name: Add target line to extra_vars.json file locally on AWX
  delegate_to: 127.0.0.1
  lineinfile:
    insertafter: '{'
    dest: '/var/lib/awx/projects/clients/{{ member_id }}/{{ subscription_id }}/extra_vars.json'
    line: '  "matrix_domain": "{{ matrix_domain }}",'
    mode: '0600'
    state: present

- name: Add matrix_awx_enabled line to extra_vars.json file locally on AWX
  delegate_to: 127.0.0.1
  lineinfile:
    insertafter: '{'
    dest: '/var/lib/awx/projects/clients/{{ member_id }}/{{ subscription_id }}/extra_vars.json'
    line: '  "matrix_awx_enabled": "true",'
    mode: '0600'
    state: present

# Create matrix_vars.yml variable file

- name: Install password generation script
  delegate_to: 127.0.0.1
  copy:
    src: ./roles/spawn-server/scripts/generate-initial-passwords.sh
    dest: /var/lib/awx/projects/hosting/generate-initial-passwords.sh
    mode: '0700'

- name: Check if matrix_vars.yml file already exists on AWX
  delegate_to: 127.0.0.1
  stat: 
    path: '/var/lib/awx/projects/clients/{{ member_id }}/{{ subscription_id }}/matrix_vars.yml'
  register: varsfile

- name: Generate initial matrix_vars.yml on AWX if it does not exist
  delegate_to: 127.0.0.1
  command: /var/lib/awx/projects/hosting/generate-initial-passwords.sh "{{ matrix_domain }}" "{{ element_subdomain }}" "{{ client_email }}" "/var/lib/awx/projects/clients/{{ member_id }}/{{ subscription_id }}/matrix_vars.yml"
  when: varsfile.stat.exists == false
  
- name: Over-write Element subdomain value if changed
  delegate_to: 127.0.0.1
  lineinfile:
    dest: '/var/lib/awx/projects/clients/{{ member_id }}/{{ subscription_id }}/matrix_vars.yml'
    regexp: "^#? *{{ item.key | regex_escape() }}:"
    line: "{{ item.key }}: {{ item.value }}"
    insertafter: '# Element Settings'
    mode: '0600'
    state: present
  with_dict:
    'matrix_server_fqn_element': '{{ element_subdomain }}.{{ matrix_domain }}'
  when: varsfile.stat.exists == true

- name: Over-write client_email value if changed
  delegate_to: 127.0.0.1
  lineinfile:
    dest: '/var/lib/awx/projects/clients/{{ member_id }}/{{ subscription_id }}/matrix_vars.yml'
    regexp: "^#? *{{ item.key | regex_escape() }}:"
    line: "  {{ item.key }}: {{ item.value }}"
    insertafter: '# Synapse Extension'
    mode: '0600'
    state: present
  with_dict:
    'admin_contact': "'mailto:{{ client_email }}'"
  when: varsfile.stat.exists == true

- name: Add matrix_nginx_proxy_base_domain_serving_enabled line to matrix_vars.yml file locally on AWX
  delegate_to: 127.0.0.1
  lineinfile:
    dest: '/var/lib/awx/projects/clients/{{ member_id }}/{{ subscription_id }}/matrix_vars.yml'
    insertafter: '# Base Domain Settings'
    line: 'matrix_nginx_proxy_base_domain_serving_enabled: false'
    mode: '0600'
    state: present
  when: base_domain_used|bool == true

- name: Add matrix_nginx_proxy_base_domain_serving_enabled line to matrix_vars.yml file locally on AWX
  delegate_to: 127.0.0.1
  lineinfile:
    dest: '/var/lib/awx/projects/clients/{{ member_id }}/{{ subscription_id }}/matrix_vars.yml'
    insertafter: '# Base Domain Settings'
    line: 'matrix_nginx_proxy_base_domain_serving_enabled: true'
    mode: '0600'
    state: present
  when: base_domain_used|bool == false

- name: Add matrix_nginx_proxy_base_domain_serving_enabled line to matrix_vars.yml file locally on AWX
  delegate_to: 127.0.0.1
  lineinfile:
    dest: '/var/lib/awx/projects/clients/{{ member_id }}/{{ subscription_id }}/matrix_vars.yml'
    insertafter: '# Base Domain Settings'
    line: 'matrix_nginx_proxy_base_domain_homepage_enabled: true'
    mode: '0600'
    state: present
  when: base_domain_used|bool == false

- name: Add matrix_jitsi_timezone line to matrix_vars.yml file locally on AWX
  delegate_to: 127.0.0.1
  lineinfile:
    dest: '/var/lib/awx/projects/clients/{{ member_id }}/{{ subscription_id }}/matrix_vars.yml'
    insertafter: '# Jitsi Settings'
    line: 'matrix_jitsi_timezone: "{{ matrix_jitsi_timezone }}"'
    mode: '0600'
    state: present
  when: matrix_jitsi_timezone is defined

- name: Add Postgresql tuning for Micro Server (s-1vcpu-2gb)
  delegate_to: 127.0.0.1
    path: '/var/lib/awx/projects/clients/{{ member_id }}/{{ subscription_id }}/matrix_vars.yml'
    insertafter: "# PostgreSQL Settings"
    block: |
      matrix_postgres_process_extra_arguments: [
        "-c max_connections=100",
        "-c shared_buffers=512MB",
        "-c effective_cache_size=1536MB",
        "-c maintenance_work_mem=128MB",
        "-c checkpoint_completion_target=0.9",
        "-c wal_buffers=16MB",
        "-c default_statistics_target=100",
        "-c random_page_cost=1.1",
        "-c effective_io_concurrency=200",
        "-c work_mem=1310kB",
        "-c min_wal_size=1GB",
        "-c max_wal_size=4GB",
        "-c synchronous_commit=off"
      ]
  when: (plan_title == "Micro DigitalOcean Server" or plan_title == "Micro On-Premises Server")
      
- name: Add Postgresql tuning for Small Server (s-2vcpu-4gb)
  delegate_to: 127.0.0.1
    path: '/var/lib/awx/projects/clients/{{ member_id }}/{{ subscription_id }}/matrix_vars.yml'
    insertafter: "# PostgreSQL Settings"
    block: |
      matrix_postgres_process_extra_arguments: [
        "-c max_connections=100",
        "-c shared_buffers=1GB",
        "-c effective_cache_size=3GB",
        "-c maintenance_work_mem=256MB",
        "-c checkpoint_completion_target=0.9",
        "-c wal_buffers=16MB",
        "-c default_statistics_target=100",
        "-c random_page_cost=1.1",
        "-c effective_io_concurrency=200",
        "-c work_mem=5242kB",
        "-c min_wal_size=1GB",
        "-c max_wal_size=4GB",
        "-c max_worker_processes=2",
        "-c max_parallel_workers_per_gather=1",
        "-c max_parallel_workers=2",
        "-c max_parallel_maintenance_workers=1",
        "-c synchronous_commit=off"
      ]
  when: (plan_title == "Small DigitalOcean Server" or plan_title == "Small On-Premises Server")
  
- name: Add Postgresql tuning for Medium Server (s-4vcpu-8gb)
  delegate_to: 127.0.0.1
    path: '/var/lib/awx/projects/clients/{{ member_id }}/{{ subscription_id }}/matrix_vars.yml'
    insertafter: "# PostgreSQL Settings"
    block: |
      matrix_postgres_process_extra_arguments: [
        "-c max_connections=100",
        "-c shared_buffers=2GB",
        "-c effective_cache_size=6GB",
        "-c maintenance_work_mem=512MB",
        "-c checkpoint_completion_target=0.9",
        "-c wal_buffers=16MB",
        "-c default_statistics_target=100",
        "-c random_page_cost=1.1",
        "-c effective_io_concurrency=200",
        "-c work_mem=5242kB",
        "-c min_wal_size=1GB",
        "-c max_wal_size=4GB",
        "-c max_worker_processes=4",
        "-c max_parallel_workers_per_gather=2",
        "-c max_parallel_workers=4",
        "-c max_parallel_maintenance_workers=2",
        "-c synchronous_commit=off"
      ]
  when: (plan_title == "Medium DigitalOcean Server" or plan_title == "Medium On-Premises Server")

- name: Add Postgresql tuning for Large Server (s-8vcpu-16gb)
  delegate_to: 127.0.0.1
    path: '/var/lib/awx/projects/clients/{{ member_id }}/{{ subscription_id }}/matrix_vars.yml'
    insertafter: "# PostgreSQL Settings"
    block: |
      matrix_postgres_process_extra_arguments: [
        "-c max_connections=100",
        "-c shared_buffers=4GB",
        "-c effective_cache_size=12GB",
        "-c maintenance_work_mem=1GB",
        "-c checkpoint_completion_target=0.9",
        "-c wal_buffers=16MB",
        "-c default_statistics_target=100",
        "-c random_page_cost=1.1",
        "-c effective_io_concurrency=200",
        "-c work_mem=5242kB",
        "-c min_wal_size=1GB",
        "-c max_wal_size=4GB",
        "-c max_worker_processes=8",
        "-c max_parallel_workers_per_gather=4",
        "-c max_parallel_workers=8",
        "-c max_parallel_maintenance_workers=4",
        "-c synchronous_commit=off"
      ]
  when: (plan_title == "Large DigitalOcean Server" or plan_title == "Large On-Premises Server")

- name: Add Postgresql tuning for Jumbo Server (so-16vcpu-128gb)
  delegate_to: 127.0.0.1
    path: '/var/lib/awx/projects/clients/{{ member_id }}/{{ subscription_id }}/matrix_vars.yml'
    insertafter: "# PostgreSQL Settings"
    block: |
      matrix_postgres_process_extra_arguments: [
        "-c max_connections=100",
        "-c shared_buffers=32GB",
        "-c effective_cache_size = 96GB",
        "-c maintenance_work_mem = 2GB",
        "-c checkpoint_completion_target=0.9",
        "-c wal_buffers=16MB",
        "-c default_statistics_target=100",
        "-c random_page_cost=1.1",
        "-c effective_io_concurrency=200",
        "-c work_mem=41943kB",
        "-c min_wal_size=1GB",
        "-c max_wal_size=4GB",
        "-c max_worker_processes=16",
        "-c max_parallel_workers_per_gather=4",
        "-c max_parallel_workers=16",
        "-c max_parallel_maintenance_workers=4",
        "-c synchronous_commit=off"
      ]
  when: (plan_title == "Jumbo DigitalOcean Server" or plan_title == "Jumbo On-Premises Server")
      
# Copy organisation.yml, server_vars.yml, extra_vars.yml, matrix_vars.yml

- name: Copy organisation.yml variables file to target
  delegate_to: "{{ server_ip_final }}"
  copy:
    src: '/var/lib/awx/projects/clients/{{ member_id }}/organisation.yml'
    dest: /matrix/awx/organisation.yml
    mode: '0660'

- name: Copy server_vars.yml variables file to target
  delegate_to: "{{ server_ip_final }}"
  copy:
    src: '/var/lib/awx/projects/clients/{{ member_id }}/{{ subscription_id }}/server_vars.yml'
    dest: /matrix/awx/server_vars.yml
    mode: '0660'

- name: Copy extra_vars.json variables file to target
  delegate_to: "{{ server_ip_final }}"
  copy:
    src: '/var/lib/awx/projects/clients/{{ member_id }}/{{ subscription_id }}/extra_vars.json'
    dest: /matrix/awx/extra_vars.json
    mode: '0660'

- name: Copy matrix_vars.yml variables file to target
  delegate_to: "{{ server_ip_final }}"
  copy:
    src: '/var/lib/awx/projects/clients/{{ member_id }}/{{ subscription_id }}/matrix_vars.yml'
    dest: /matrix/awx/matrix_vars.yml
    mode: '0660'


