# Spawn a Server
- import_tasks: "{{ role_path }}/tasks/spawn_do_droplet.yml"
  tags: digitalocean-droplet

# Spawn a 'Space'
- import_tasks: "{{ role_path }}/tasks/spawn_do_space.yml"
  tags: digitalocean-space

# Connects an existing BYO server
- import_tasks: "{{ role_path }}/tasks/connect_byo_server.yml"
  tags: byo-server

# Create initial variable files
- import_tasks: "{{ role_path }}/tasks/generate_initial_variables.yml"
