
# Need section to convert do_droplet_region_long to a valid shortcode:
# New York City (USA) = nyc1, nyc3
# San Francisco (USA) = sfo2, sfo3
# Amsterdam (NLD) = ams3
# Frankfurt (DEU) = fra1
# Singapore (SGP) = sgp1
# London (GBR) = lon1
# Toronto (CAN) = tor1
# Balgalore (IND) = blr1

- name: Set valid digitalocean area code for New York City.
  delegate_to: 127.0.0.1
  set_fact:
    do_droplet_region: "nyc3"
    matrix_jitsi_timezone: "America/New_York"
  when: (subscription_type == "digitalocean" and do_droplet_region_long == "New York City (USA)")

- name: Set valid digitalocean area code for San Francisco.
  delegate_to: 127.0.0.1
  set_fact:
    do_droplet_region: "sfo3"
    matrix_jitsi_timezone: "America/Los_Angeles"
  when: (subscription_type == "digitalocean" and do_droplet_region_long == "San Francisco (USA)")

- name: Set valid digitalocean area code for Amsterdam.
  delegate_to: 127.0.0.1
  set_fact:
    do_droplet_region: "ams3"
    matrix_jitsi_timezone: "Europe/Amsterdam"
  when: (subscription_type == "digitalocean" and do_droplet_region_long == "Amsterdam (NLD)")

- name: Set valid digitalocean area code for Frankfurt.
  delegate_to: 127.0.0.1
  set_fact:
    do_droplet_region: "fra1"
    matrix_jitsi_timezone: "Europe/Berlin"
  when: (subscription_type == "digitalocean" and do_droplet_region_long == "Frankfurt (DEU)")

- name: Set valid digitalocean area code for Singapore.
  delegate_to: 127.0.0.1
  set_fact:
    do_droplet_region: "sgp1"
    matrix_jitsi_timezone: "Singapore"
  when: (subscription_type == "digitalocean" and do_droplet_region_long == "Singapore (SGP)")

- name: Set valid digitalocean area code for London.
  delegate_to: 127.0.0.1
  set_fact:
    do_droplet_region: "lon1"
    matrix_jitsi_timezone: "Europe/London"
  when: (subscription_type == "digitalocean" and do_droplet_region_long == "London (GBR)")

- name: Set valid digitalocean area code for Toronto.
  delegate_to: 127.0.0.1
  set_fact:
    do_droplet_region: "tor1"
    matrix_jitsi_timezone: "America/Toronto"
  when: (subscription_type == "digitalocean" and do_droplet_region_long == "Toronto (CAN)")

- name: Set valid digitalocean area code for Balgalore.
  delegate_to: 127.0.0.1
  set_fact:
    do_droplet_region: "blr1"
    matrix_jitsi_timezone: "Asia/Kolkata"
  when: (subscription_type == "digitalocean" and do_droplet_region_long == "Balgalore (IND)")

- name: Set MAU limit for Micro Server
  delegate_to: 127.0.0.1
  set_fact:
    slug_size: "s-1vcpu-2gb"
    swap_size: "2G"
    mau_limit: 5
  when: (subscription_type == "digitalocean" and plan_title == "Micro DigitalOcean Server")

- name: Set MAU limit for Small Server
  delegate_to: 127.0.0.1
  set_fact:
    slug_size: "s-2vcpu-4gb"
    swap_size: "4G"
    mau_limit: 25
  when: (subscription_type == "digitalocean" and plan_title == "Small DigitalOcean Server")

- name: Set MAU limit for Medium Server
  delegate_to: 127.0.0.1
  set_fact:
    slug_size: "s-4vcpu-8gb"
    swap_size: "8G"
    mau_limit: 50
  when: (subscription_type == "digitalocean" and plan_title == "Medium DigitalOcean Server")

- name: Set MAU limit for Large Server
  delegate_to: 127.0.0.1
  set_fact:
    slug_size: "s-8vcpu-16gb"
    swap_size: "16G"
    mau_limit: 100
  when: (subscription_type == "digitalocean" and plan_title == "Large DigitalOcean Server")

- name: Set MAU limit for Jumbo Server
  delegate_to: 127.0.0.1
  set_fact:
    slug_size: "so-16vcpu-128gb"
    swap_size: "64G"
    mau_limit: 1000
  when: (subscription_type == "digitalocean" and plan_title == "Jumbo DigitalOcean Server")

- name: do_droplet_region line to server_vars.yml file locally on AWX
  delegate_to: 127.0.0.1
  lineinfile:
    dest: '/var/lib/awx/projects/clients/{{ member_id }}/{{ subscription_id }}/server_vars.yml'
    line: 'do_droplet_region: {{ do_droplet_region }}'
    mode: '0600'
    state: present
  when: subscription_type == "digitalocean"

- name: 
  delegate_to: 127.0.0.1
  community.digitalocean.digital_ocean_sshkey_info:
    oauth_token: '{{ do_api_token }}'
  register: ssh_keys

- debug:
    msg: "{{ ssh_keys }}"
  when: subscription_type == "digitalocean"

- name: Build an array of all the ssh key ids
  delegate_to: 127.0.0.1
  set_fact:
    ssh_key_id_array: "{{ ssh_key_id_array }} + [ '{{ item.id }}' ]"
  with_items: "{{ ssh_keys.data }}"
  when: subscription_type == "digitalocean"

- debug:
    msg: "{{ ssh_key_id_array }}"
  when: subscription_type == "digitalocean"

- name: Spawn a new Digital Ocean Droplet
  delegate_to: 127.0.0.1
  community.digitalocean.digital_ocean_droplet:
    state: present
    name: '{{ matrix_domain }}'
    oauth_token: '{{ do_api_token }}'
    size: '{{ slug_size }}'
    ssh_keys: '{{ ssh_key_id_array }}'
    region: '{{ do_droplet_region }}'
    image: '{{ do_image }}'
    ipv6: yes
    wait: yes
    unique_name: yes
  register: new_server_info
  when: subscription_type == "digitalocean"

- debug:
    msg: "{{ new_server_info }}"
  when: subscription_type == "digitalocean"

- debug:
    msg: "{{ new_server_info.data.droplet }}"
  when: subscription_type == "digitalocean"

- name: Assign server IPs to variables
  delegate_to: 127.0.0.1
  set_fact:
    server_ipv4: "{{ new_server_info.data.ip_address }}"
    server_ipv6: "{{ new_server_info.data.ipv6_address }}"
  when: subscription_type == "digitalocean"

- debug:
    msg: "{{ server_ipv4 }}"
  when: subscription_type == "digitalocean"

- debug:
    msg: "{{ server_ipv6 }}"
  when: subscription_type == "digitalocean"

