
- name: Install imposter-check script
  copy:
    src: ./roles/imposter-check/scripts/imposter-check.py
    dest: /var/lib/awx/projects/hosting/imposter-check.py
    mode: '0700'

- name: Run imposter-check script and collect output
  command: /usr/bin/python3 /var/lib/awx/projects/hosting/imposter-check.py "{{ matrix_domain }}" "{{ subscription_id }}"
  register: impostercheck

- debug: msg="{{ impostercheck.stdout }}"

- debug: msg="This address is already in use by another member, please enter your own domain address. Contact the administrator if you believe this is an error."
  when: impostercheck.stdout|bool == true

- meta: end_play
  when: impostercheck.stdout|bool == true



