
# Load hosting and droplet variables from AWX file
- import_tasks: "{{ role_path }}/tasks/imposter_check.yml"
  tags: imposter-check

# Load hosting and droplet variables from AWX file
- import_tasks: "{{ role_path }}/tasks/load_variables.yml"
  tags: always

