
- name: Copy ssh_sftp.service file
  copy:
    src: './inventory/templates/ssh_sftp.service'
    dest: '/lib/systemd/system/ssh_sftp.service'
    mode: 0644

- name: Copy sshd config file
  copy:
    src: './inventory/templates/sshd_sftp_config'
    dest: '/etc/ssh/sshd_sftp_config'
    mode: 0644

- name: Create the base domain website directory if it doesn't exist
  delegate_to: '{{ server_ipv4 }}'
  file:
    path: /matrix/nginx-proxy/data/matrix-domain/
    state: directory
    mode: '0666'

- name: Generate SFTP users password
  delegate: '{{ server_ipv4 }}'
  shell: pwgen -s 20 1
  register: website_password

- name: Add the SFTP user 'website' with a primary group of 'website', and a shell of /bin/false
  delegate_to: '{{ server_ipv4 }}'
  user:
    name: website
    comment: SFTP user to set custom web files
    shell: /bin/false
    home: /home/website/
    password: '{{ website_password.stdout }}'
    group: website

- name: Setup SFTP users default root path
  delegate_to: '{{ server_ipv4 }}'
  shell: sudo usermod -d / website

- name: Create a symbolic link
  delegate_to: '{{ server_ipv4 }}'
  file:
    src: /matrix/nginx-proxy/data/matrix-domain/
    dest: /home/website/
    owner: root
    group: root
    state: link

- name: Enable service ssh_sftp.service
  service:
    name: ssh_sftp.service
    enabled: yes

- name: Enable service ssh_sftp.service
  service:
    name: ssh_sftp.service
    start: started

