
- name: Copy ssh_sftp.service file
  delegate_to: '{{ server_ipv4 }}'
  copy:
    src: './inventory/templates/ssh_sftp.service'
    dest: '/lib/systemd/system/ssh_sftp.service'
    mode: 0644

- name: Copy sshd config file
  delegate_to: '{{ server_ipv4 }}'
  copy:
    src: './inventory/templates/sshd_sftp_config'
    dest: '/etc/ssh/sshd_sftp_config'
    mode: 0644

- name: Generate SFTP users password
  delegate_to: 127.0.0.1
  shell: pwgen -s 20 1
  register: website_password

- name: Ensure group "website" exists
  delegate_to: '{{ server_ipv4 }}'
  group:
    name: website
    state: present

- name: Add the SFTP user 'website' with a primary group of 'website', and a shell of /bin/false
  delegate_to: '{{ server_ipv4 }}'
  user:
    name: website
    comment: SFTP user to set custom web files
    shell: /bin/false
    home: /home/website/
    password: '{{ website_password.stdout }}'
    group: website

- name: Setup SFTP users default root path
  delegate_to: '{{ server_ipv4 }}'
  shell: sudo usermod -d / website

- name: Create the ro /chroot directory if it doesn't exist. (/chroot/website has website:website permissions and is mounted to nginx container)
  delegate_to: '{{ server_ipv4 }}'
  file:
    path: /chroot
    state: directory
    owner: root
    group: root
    mode: '0744'

- name: Create the rw /chroot/website directory if it doesn't exist.
  delegate_to: '{{ server_ipv4 }}'
  file:
    path: /chroot/website
    state: directory
    owner: website
    group: website
    mode: '0766'

- name: Enable service ssh_sftp.service
  delegate_to: '{{ server_ipv4 }}'
  service:
    name: ssh_sftp.service
    enabled: yes

- name: Start service ssh_sftp.service
  delegate_to: '{{ server_ipv4 }}'
  service:
    name: ssh_sftp.service
    state: started

