
# Perform initial server setup
- import_tasks: "{{ role_path }}/tasks/setup_server.yml"
  tags: always

# Perform firewall setup
- import_tasks: "{{ role_path }}/tasks/setup_firewall.yml"
  tags: setup-firewall

# Setup server export
- import_tasks: "{{ role_path }}/tasks/setup_export.yml"
  tags: setup-export
  
# Setup server backup
- import_tasks: "{{ role_path }}/tasks/setup_backup.yml"
  when: backup_server_enabled|bool
  tags: setup-backup

# Setup MailGun service
- import_tasks: "{{ role_path }}/tasks/setup_mailgun.yml"
  tags: setup-mailgun

