
# Perform initial server setup
- import_tasks: "{{ role_path }}/tasks/setup_server.yml"
  tags: always

# Setup server export
- import_tasks: "{{ role_path }}/tasks/setup_export.yml"
  tags: setup-export
  
# Setup server backup
- import_tasks: "{{ role_path }}/tasks/setup_backup.yml"
  tags: setup-backup

