
# Perform initial server setup
- import_tasks: "{{ role_path }}/tasks/setup_server.yml"
  tags: always

# Setup Server Backup
- import_tasks: "{{ role_path }}/tasks/setup_backup.yml"
  tags: setup-backup

