
- name: Install necessary utils on target machine
  delegate_to: "matrix.{{ matrix_domain }}"
  apt:
    pkg:
     - pigz
     - at

- name: Ensure group "sftp" exists
  delegate_to: "matrix.{{ matrix_domain }}"
  group:
    name: sftp
    state: present

- name: Ensure group "matrix" exists
  delegate_to: "matrix.{{ matrix_domain }}"
  group:
    name: matrix
    state: present

- name: If user account doesn't exist, create a disabled account for SFTP user 'sftp', with a primary group of 'sftp', and a shell of /bin/false
  delegate_to: "matrix.{{ matrix_domain }}"
  user:
    name: sftp
    comment: SFTP user to set custom web files
    shell: /bin/false
    home: /home/sftp/
    group: sftp
    password: '!'
    update_password: on_create

- name: If user account doesn't exist, create a disabled account for Matrix user 'matrix', with a primary group of 'matrix', and a shell of /bin/false
  delegate_to: "matrix.{{ matrix_domain }}"
  user:
    name: matrix
    comment: Matrix user, initialised early incase of /chroot/export/ recovery.
    home: /home/matrix/
    group: matrix
    password: '!'
    update_password: on_create

- name: Create the ro /chroot directory with sticky bit if it doesn't exist. (/chroot/website has matrix:matrix permissions and is mounted to nginx container)
  delegate_to: "matrix.{{ matrix_domain }}"
  file:
    path: /chroot
    state: directory
    owner: root
    group: root
    mode: '1755'

- name: Create the rw /chroot/website directory if it doesn't exist.
  delegate_to: "matrix.{{ matrix_domain }}"
  file:
    path: /chroot/website
    state: directory
    owner: matrix
    group: matrix
    mode: '0574'
  when: base_domain_used == 'false'

- name: Ensure /chroot/export/ location exists
  delegate_to: "matrix.{{ matrix_domain }}"
  file:
    path: /chroot/export
    state: directory
    owner: sftp
    group: sftp
    mode: '0700'

- name: Install awx-export-service.sh script is installed
  delegate_to: "matrix.{{ matrix_domain }}"
  copy:
    src: ./roles/setup-server/scripts/awx-export-service.sh
    dest: /usr/local/bin/awx-export-service.sh
    mode: '0700'

- name: Touch the export.log file
  delegate_to: "matrix.{{ matrix_domain }}"
  file:
    path: /matrix/awx/export.log
    state: touch
    owner: root
    group: root
    mode: '0644'

