
- name: Update repositories and all packages on target machine
  delegate_to: "matrix.{{ matrix_domain }}"
  apt:
    name: "*"
    update_cache: yes

- name: Install necessary utils on target machine
  delegate_to: "matrix.{{ matrix_domain }}"
  apt:
    pkg:
     - ansible
     - etckeeper
     - git
     - openssl
     - prometheus-node-exporter
      
- name: Create swapfile with the right permissions
  delegate_to: "matrix.{{ matrix_domain }}"
  command: 'fallocate -l {{ swap_size }} /swapfile'
  register: swapfile_new
  args:
    creates: /swapfile
    
- name: Set correct permissions on swapfile
  delegate_to: "matrix.{{ matrix_domain }}"
  command: 'chmod 600 /swapfile'
  when: swapfile_new.delta is defined

- name: Make swapfile
  delegate_to: "matrix.{{ matrix_domain }}"
  command: 'mkswap /swapfile'
  when: swapfile_new.delta is defined
  
- name: Make swapfile
  delegate_to: "matrix.{{ matrix_domain }}"
  command: 'swapon /swapfile'
  when: swapfile_new.delta is defined

- name: Make swapfile permanent in /etc/fstab
  delegate_to: "matrix.{{ matrix_domain }}"
  mount: name=none
         src=/swapfile
         fstype=swap
         opts=sw
         passno=0
         dump=0
         state=present

- name: Set swappiness to 20
  delegate_to: "matrix.{{ matrix_domain }}"
  shell: sysctl vm.swappiness=20

- name: Set swappiness to 20 on reboot
  delegate_to: "matrix.{{ matrix_domain }}"
  lineinfile:
    path: /etc/sysctl.conf
    line: vm.swappiness=20
    owner: root
    group: root
    mode: '0644'

- name: Examine if docker is already installed
  delegate_to: "matrix.{{ matrix_domain }}"
  shell: apt list docker-ce
  register: docker_installed

# Docker logs pruning, only applied if docker is already installed

- name: Ensure docker config folder exists
  delegate_to: "matrix.{{ matrix_domain }}"
  file:
    path: '/etc/docker/'
    owner: root
    group: root
    mode: '0755'
    state: directory
  when: '"installed" in docker_installed.stdout'

- name: Save docker config file, template
  delegate_to: "matrix.{{ matrix_domain }}"
  template:
    src: '{{ role_path }}/templates/daemon.json.j2'
    dest: '/etc/docker/daemon.json'
  when: '"installed" in docker_installed.stdout'

- name: Creates a crontab entry for trimming systemd logs
  delegate_to: "matrix.{{ matrix_domain }}"
  cron:
    name: "Trim Systemd Logs"
    user: root
    special_time: daily
    job: "sudo journalctl --vacuum-time=28d"

