
- name: Reload matrix server variables from matrix_vars.yml
  include_vars:
    file: /var/lib/awx/projects/clients/{{ member_id }}/{{ subscription_id }}/matrix_vars.yml
  no_log: True

- name: Create MailGun SMTP login
  delegate_to: 127.0.0.1
  shell: |
    curl -s --user 'api:{{ mg_private_api_key }}' -G https://{{ mg_api_url }}/v3/domains/{{ mg_sender_domain }}/credentials -F login='{{ matrix_domain }}@{{ mg_sender_domain }}' -F password='{{ matrix_mailer_relay_auth_password }}'
#  no_log: True


