
- name: Install necessary utils on target machine
  delegate_to: "{{ server_ip_final }}"
  apt:
    pkg:
     - borgbackup
     - borgmatic
     - pigz

- name: Create the /chroot directory if it doesn't exist.
  delegate_to: "{{ server_ip_final }}"
  file:
    path: /chroot
    state: directory
    owner: root
    group: root
    mode: '1755'

- name: Ensure /chroot/backup/ location exists
  delegate_to: "{{ server_ip_final }}"
  file:
    path: /chroot/backup
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Ensure /chroot/backup/borg/ location exists
  delegate_to: "{{ server_ip_final }}"
  file:
    path: /chroot/backup/borg
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Ensure /backup/snapshot/ location exists
  delegate_to: "{{ server_ip_final }}"
  file:
    path: /chroot/backup/snapshot
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Ensure borgmatic config directory exists
  delegate_to: "{{ server_ip_final }}"
  file:
    path: /root/.config/borgmatic
    state: directory
    owner: root
    group: root
    mode: '0700'

- name: Save new 'Provision Server' survey.json to the AWX tower, template
  delegate_to: "{{ server_ip_final }}"
  template:
    src: './roles/setup-server/templates/config.yaml.j2'
    dest: '/root/.config/borgmatic/config.yaml'

- name: Run the 'borg init' command
  delegate_to: "{{ server_ip_final }}"
  command: 'borg init --encryption=none /chroot/backup/borg'
  args: 
    creates: /chroot/backup/borg/README

# ^ This step can be skipped after Debian 11 :)

- name: Install backup.sh script is installed
  delegate_to: "{{ server_ip_final }}"
  copy:
    src: ./roles/setup-server/scripts/backup.sh
    dest: /root/backup.sh
    mode: '0700'

- name: Touch the backup.log file
  delegate_to: "{{ server_ip_final }}"
  file:
    path: /matrix/awx/backup.log
    state: touch
    owner: root
    group: root
    mode: '0644'

- name: Creates a crontab entry for backup.sh
  delegate_to: "{{ server_ip_final }}"
  cron:
    name: "Snapshot database and run borgmatic"
    user: root
    special_time: hourly
    job: "/root/backup.sh"

