
- name: Update repositories and all packages on target machine
  delegate_to: "{{ server_ip_final }}"
  apt:
    name: "*"
    update_cache: yes

- name: Install necessary utils on target machine
  delegate_to: "{{ server_ip_final }}"
  apt:
    pkg:
     - ansible
     - etckeeper
     - git
     - openssl
     - prometheus-node-exporter
      
- name: Create swapfile with the right permissions
  command: 'fallocate -l {{ swap_size }} /swapfile'
  register: swapfile_new
  args:
    creates: /swapfile
    
- name: Set correct permissions on swapfile
  command: 'chmod 600 /swapfile'
  when: swapfile_new.delta is defined

- name: Make swapfile
  command: 'mkswap /swapfile'
  when: swapfile_new.delta is defined
  
- name: Make swapfile
  command: 'swapon /swapfile'
  when: swapfile_new.delta is defined

- name: Make swapfile permanent in /etc/fstab
  delegate_to: "{{ server_ip_final }}"
  mount: name=none
    src=/swapfile
    fstype=swap
    opts=sw
    passno=0
    dump=0
    state=present

