
- name: Add specified repository into sources list
  delegate_to: "{{ server_ip_final }}"
  apt_repository:
    repo: deb http://deb.debian.org/debian buster-backports main
    state: present

- name: Install necessary utils on target machine
  delegate_to: "{{ server_ip_final }}"
  apt:
    pkg:
     - pigz

- name: If user account doesn't exist, create a disabled account for SFTP user 'sftp', with a primary group of 'sftp', and a shell of /bin/false
  user:
    name: sftp
    comment: SFTP user to set custom web files
    shell: /bin/false
    home: /home/sftp/
    group: sftp
    password: '!'
    update_password: on_create

- name: Create the ro /chroot directory with sticky bit if it doesn't exist. (/chroot/website has matrix:matrix permissions and is mounted to nginx container)
  file:
    path: /chroot
    state: directory
    owner: root
    group: root
    mode: '1755'

- name: Create the rw /chroot/website directory if it doesn't exist.
  file:
    path: /chroot/website
    state: directory
    owner: matrix
    group: matrix
    mode: '0474'

- name: Ensure /chroot/backup/ location exists
  file:
    path: /chroot/backup
    state: directory
    owner: sftp
    group: sftp
    mode: '0700'

- name: Ensure /chroot/backup/matrix/ location exists
  file:
    path: /chroot/backup/borg
    state: directory
    owner: sftp
    group: sftp
    mode: '0700'

- name: Ensure /chroot/backup/snapshot/ location exists
  file:
    path: /chroot/backup/snapshot
    state: directory
    owner: sftp
    group: sftp
    mode: '0700'

- name: Save new 'Provision Server' survey.json to the AWX tower, template
  delegate_to: "{{ server_ip_final }}"
  template:
    src: './roles/setup-server/templates/config.yaml.j2'
    dest: '/root/.config/borgmatic/config.yaml'

- name: Run the 'borg init' command
  delegate_to: "{{ server_ip_final }}"
  command: 'borg init --encryption=none /chroot/backup/borg'
  args: 
    creates: /chroot/backup/borg/README

# ^ This step can be skipped after Debian 11 :)

- name: Install backup.sh script is installed
  delegate_to: "{{ server_ip_final }}"
  copy:
    src: ./roles/setup-server/scripts/backup.sh
    dest: /root/backup.sh
    mode: '0700'

- name: Touch the backup.log file
  delegate_to: "{{ server_ip_final }}"
  file:
    path: /matrix/awx/backup.log
    state: touch
    owner: root
    group: root
    mode: '0644'

- name: Creates a crontab entry for backup.sh
  delegate_to: "{{ server_ip_final }}"
  cron:
    name: "Snapshot database and run borgmatic"
    user: root
    special_time: hourly
    job: "/root/backup.sh"

